/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const SubscriptionTier = IDL.Variant({
  'pro' : IDL.Null,
  'free' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'followersCount' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'tier' : SubscriptionTier,
  'isBanned' : IDL.Bool,
  'isAdmin' : IDL.Bool,
  'followingCount' : IDL.Nat,
  'isFlagged' : IDL.Bool,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostId = IDL.Nat;
export const CreateCommentInput = IDL.Record({ 'content' : IDL.Text });
export const CommentId = IDL.Nat;
export const Comment = IDL.Record({
  'id' : CommentId,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'authorPrincipal' : UserId,
  'postId' : PostId,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const PersonalityType = IDL.Variant({
  'mentor' : IDL.Null,
  'romantic' : IDL.Null,
  'businessCoach' : IDL.Null,
  'friendly' : IDL.Null,
});
export const CreateCompanionInput = IDL.Record({
  'customTraits' : IDL.Text,
  'name' : IDL.Text,
  'personalityType' : PersonalityType,
});
export const CompanionId = IDL.Nat;
export const AICompanion = IDL.Record({
  'id' : CompanionId,
  'ownerPrincipal' : UserId,
  'customTraits' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'personalityType' : PersonalityType,
});
export const CreatePostInput = IDL.Record({ 'content' : IDL.Text });
export const Post = IDL.Record({
  'id' : PostId,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'commentsCount' : IDL.Nat,
  'likesCount' : IDL.Nat,
  'authorPrincipal' : UserId,
});
export const MessageId = IDL.Nat;
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'role' : IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null }),
  'companionId' : CompanionId,
  'timestamp' : Timestamp,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const RegisterInput = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateProfileInput = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'adminBanUser' : IDL.Func([UserId], [], []),
  'adminFlagUser' : IDL.Func([UserId], [], []),
  'adminGetUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'commentPost' : IDL.Func([PostId, CreateCommentInput], [Comment], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCompanion' : IDL.Func([CreateCompanionInput], [AICompanion], []),
  'createPost' : IDL.Func([CreatePostInput], [Post], []),
  'deleteCompanion' : IDL.Func([CompanionId], [], []),
  'followUser' : IDL.Func([UserId], [], []),
  'getAIUsageCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
  'getCompanion' : IDL.Func([CompanionId], [IDL.Opt(AICompanion)], ['query']),
  'getCompanions' : IDL.Func([], [IDL.Vec(AICompanion)], ['query']),
  'getFeedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
  'getFollowing' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
  'getMessages' : IDL.Func([CompanionId], [IDL.Vec(Message)], ['query']),
  'getPosts' : IDL.Func([UserId], [IDL.Vec(Post)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSubscriptionStatus' : IDL.Func([], [SubscriptionTier], ['query']),
  'getUser' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([PostId], [], []),
  'registerUser' : IDL.Func([RegisterInput], [UserProfile], []),
  'sendMessage' : IDL.Func([CompanionId, IDL.Text], [Message], []),
  'setOpenAiApiKey' : IDL.Func([IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unfollowUser' : IDL.Func([UserId], [], []),
  'updateAvatar' : IDL.Func([ExternalBlob], [], []),
  'updateProfile' : IDL.Func([UpdateProfileInput], [UserProfile], []),
  'upgradeToPro' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const SubscriptionTier = IDL.Variant({ 'pro' : IDL.Null, 'free' : IDL.Null });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'followersCount' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'tier' : SubscriptionTier,
    'isBanned' : IDL.Bool,
    'isAdmin' : IDL.Bool,
    'followingCount' : IDL.Nat,
    'isFlagged' : IDL.Bool,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostId = IDL.Nat;
  const CreateCommentInput = IDL.Record({ 'content' : IDL.Text });
  const CommentId = IDL.Nat;
  const Comment = IDL.Record({
    'id' : CommentId,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'authorPrincipal' : UserId,
    'postId' : PostId,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const PersonalityType = IDL.Variant({
    'mentor' : IDL.Null,
    'romantic' : IDL.Null,
    'businessCoach' : IDL.Null,
    'friendly' : IDL.Null,
  });
  const CreateCompanionInput = IDL.Record({
    'customTraits' : IDL.Text,
    'name' : IDL.Text,
    'personalityType' : PersonalityType,
  });
  const CompanionId = IDL.Nat;
  const AICompanion = IDL.Record({
    'id' : CompanionId,
    'ownerPrincipal' : UserId,
    'customTraits' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'personalityType' : PersonalityType,
  });
  const CreatePostInput = IDL.Record({ 'content' : IDL.Text });
  const Post = IDL.Record({
    'id' : PostId,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'commentsCount' : IDL.Nat,
    'likesCount' : IDL.Nat,
    'authorPrincipal' : UserId,
  });
  const MessageId = IDL.Nat;
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'role' : IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null }),
    'companionId' : CompanionId,
    'timestamp' : Timestamp,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const RegisterInput = IDL.Record({ 'bio' : IDL.Text, 'name' : IDL.Text });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateProfileInput = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'adminBanUser' : IDL.Func([UserId], [], []),
    'adminFlagUser' : IDL.Func([UserId], [], []),
    'adminGetUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'commentPost' : IDL.Func([PostId, CreateCommentInput], [Comment], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCompanion' : IDL.Func([CreateCompanionInput], [AICompanion], []),
    'createPost' : IDL.Func([CreatePostInput], [Post], []),
    'deleteCompanion' : IDL.Func([CompanionId], [], []),
    'followUser' : IDL.Func([UserId], [], []),
    'getAIUsageCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
    'getCompanion' : IDL.Func([CompanionId], [IDL.Opt(AICompanion)], ['query']),
    'getCompanions' : IDL.Func([], [IDL.Vec(AICompanion)], ['query']),
    'getFeedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
    'getFollowing' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
    'getMessages' : IDL.Func([CompanionId], [IDL.Vec(Message)], ['query']),
    'getPosts' : IDL.Func([UserId], [IDL.Vec(Post)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSubscriptionStatus' : IDL.Func([], [SubscriptionTier], ['query']),
    'getUser' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([PostId], [], []),
    'registerUser' : IDL.Func([RegisterInput], [UserProfile], []),
    'sendMessage' : IDL.Func([CompanionId, IDL.Text], [Message], []),
    'setOpenAiApiKey' : IDL.Func([IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unfollowUser' : IDL.Func([UserId], [], []),
    'updateAvatar' : IDL.Func([ExternalBlob], [], []),
    'updateProfile' : IDL.Func([UpdateProfileInput], [UserProfile], []),
    'upgradeToPro' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };