/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AICompanion {
  'id' : CompanionId,
  'ownerPrincipal' : UserId,
  'customTraits' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'personalityType' : PersonalityType,
}
export interface Comment {
  'id' : CommentId,
  'content' : string,
  'createdAt' : Timestamp,
  'authorPrincipal' : UserId,
  'postId' : PostId,
}
export type CommentId = bigint;
export type CompanionId = bigint;
export interface CreateCommentInput { 'content' : string }
export interface CreateCompanionInput {
  'customTraits' : string,
  'name' : string,
  'personalityType' : PersonalityType,
}
export interface CreatePostInput { 'content' : string }
export type ExternalBlob = Uint8Array;
export interface Message {
  'id' : MessageId,
  'content' : string,
  'role' : { 'user' : null } |
    { 'assistant' : null },
  'companionId' : CompanionId,
  'timestamp' : Timestamp,
}
export type MessageId = bigint;
export type PersonalityType = { 'mentor' : null } |
  { 'romantic' : null } |
  { 'businessCoach' : null } |
  { 'friendly' : null };
export interface Post {
  'id' : PostId,
  'content' : string,
  'createdAt' : Timestamp,
  'commentsCount' : bigint,
  'likesCount' : bigint,
  'authorPrincipal' : UserId,
}
export type PostId = bigint;
export interface RegisterInput { 'bio' : string, 'name' : string }
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type SubscriptionTier = { 'pro' : null } |
  { 'free' : null };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateProfileInput { 'bio' : string, 'name' : string }
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'bio' : string,
  'followersCount' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'tier' : SubscriptionTier,
  'isBanned' : boolean,
  'isAdmin' : boolean,
  'followingCount' : bigint,
  'isFlagged' : boolean,
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'adminBanUser' : ActorMethod<[UserId], undefined>,
  'adminFlagUser' : ActorMethod<[UserId], undefined>,
  'adminGetUsers' : ActorMethod<[], Array<UserProfile>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'commentPost' : ActorMethod<[PostId, CreateCommentInput], Comment>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCompanion' : ActorMethod<[CreateCompanionInput], AICompanion>,
  'createPost' : ActorMethod<[CreatePostInput], Post>,
  'deleteCompanion' : ActorMethod<[CompanionId], undefined>,
  'followUser' : ActorMethod<[UserId], undefined>,
  'getAIUsageCount' : ActorMethod<[], bigint>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[PostId], Array<Comment>>,
  'getCompanion' : ActorMethod<[CompanionId], [] | [AICompanion]>,
  'getCompanions' : ActorMethod<[], Array<AICompanion>>,
  'getFeedPosts' : ActorMethod<[], Array<Post>>,
  'getFollowers' : ActorMethod<[UserId], Array<UserId>>,
  'getFollowing' : ActorMethod<[UserId], Array<UserId>>,
  'getMessages' : ActorMethod<[CompanionId], Array<Message>>,
  'getPosts' : ActorMethod<[UserId], Array<Post>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSubscriptionStatus' : ActorMethod<[], SubscriptionTier>,
  'getUser' : ActorMethod<[UserId], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[PostId], undefined>,
  'registerUser' : ActorMethod<[RegisterInput], UserProfile>,
  'sendMessage' : ActorMethod<[CompanionId, string], Message>,
  'setOpenAiApiKey' : ActorMethod<[string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unfollowUser' : ActorMethod<[UserId], undefined>,
  'updateAvatar' : ActorMethod<[ExternalBlob], undefined>,
  'updateProfile' : ActorMethod<[UpdateProfileInput], UserProfile>,
  'upgradeToPro' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];